###
mode: training
unet: 1
cond_scale: 1.75
seed: 42
idx: 0
iterations: 1000

###
trainer:
  lr: 1e-4

  split_valid_from_train: false
  dl_tuple_output_keywords_names: [images, text_embeds]

###
display_samples: True
validate_at_every: 10
sample_at_every: 500
save_at_every: 500

###
testing:
  save_samples: True
  save_image_tensors: True

  lower_batch: 0
  upper_batch: 160

  # Frechet Inception Distance
  FrechetInceptionDistance:
    usage: True
    params:
      feature: 2048
      reset_real_features: True
      normalize: True

  # Kernel Inception Distance
  KernelInceptionDistance:
    usage: True
    params:
      feature: 2048
      subsets: 50
      subset_size: 512
      reset_real_features: True
      normalize: True

  # Clean Fréchet Inception Distance
  CleanFID:
    usage: True
    params:
      mode: clean
      model_name: inception_v3
      num_workers: 4
      batch_size: 32 

  # Fréchet CLIP Distance
  FrechetCLIPDistance:
    usage: True
    params:
      mode: clean
      model_name: clip_vit_b_32
      num_workers: 4
      batch_size: 32 

  # LearnedPerceptualImagePatchSimilarity
  LearnedPerceptualImagePatchSimilarity:
    usage: False
    params:
      net_type: vgg

  # CMMD
  CMMD:
    usage: True
    params:
      batch_size: 32
      max_count: -1

###
wandb:
  usage: False
  wandb_prj: MultiphaseBioImgGen
  wandb_entity: dgbeo2003

###
tensorboard:
  usage: False