program: src/testing/testing_imagen.py
method: grid
name: sweep_cond_scale
metrics:
  - name: FID
    goal: minimize
  - name: Clean_FID
    goal: minimize
  - name: LPIPS
    goal: minimize
  - name: KID
    goal: minimize

parameters:
  conductor.config_index:
    values: [0, 1, 2, 3]

command:
  - python
  - ${program}
  - ${args_no_hyphens}
  - conductor.mode=testing
  - conductor.unet_number=1
  - models.imagen.timesteps=250
  - conductor.trainer.idx=0
  - conductor.trainer.batch_size=64
  - utils.wandb.usage=True
  - utils.log.usage=True