name: imagen
imagen:
  video: false
  timesteps: [1024, 512]
  image_sizes: [64, 256]
  random_crop_sizes: [null, 64]
  condition_on_text: true
  cond_drop_prob: 0.1
  text_encoder_name: google/t5-v1_1-base # google/t5-v1_1-large

  unets:
    - dim: 128
      dim_mults: [1, 2, 3, 4]
      num_resnet_blocks: 3
      layer_attns: [false, true, true, true]
      layer_cross_attns: [false, true, true, true]
      attn_heads: 8

    - dim: 128
      dim_mults: [1, 2, 4, 8]
      num_resnet_blocks: [2, 4, 8, 8]
      layer_attns: [false, false, false, true]
      layer_cross_attns: [false, false, false, true]
      attn_heads: 8
