seed: 42
model:
  model_type: Imagen

### Earlystopping
early_stopping:
  patience: 3000
  min_delta: 0.001

### Trainer
trainer:
  multi_gpu: False
  use_existing_model: False

  split_valid_from_train: False
  dl_tuple_output_keywords_names: [images, text_embeds]

  ### DataLoader:
  batch_size: 8
  num_workers: 8
  pin_memory: True

  ## Training
  idx: 0
  iterations: 100000
  unet_number: 1

  PATH_MODEL_CHECKPOINT: ./asset/results/training/VinDrMultiphase_Imagen_unet1/exp_0/model/fold1_checkpoint.pt
  PATH_MODEL_LOAD: ./asset/results/training/VinDrMultiphase_Imagen_unet1/exp_0/model/fold1_checkpoint.pt
  PATH_MODEL_SAVE: ./asset/results/training/VinDrMultiphase_Imagen_unet2/exp_0/model/fold1_checkpoint.pt

### Validation
validation:
  path_training_sample: ./asset/results/training
  display_sample: True
  
  interval:
    valid_loss: 50
    validate_model: 5000

  sample_quantity: 1
  cond_scale_validation: 7

### Testing
testing:
  PATH_MODEL_TESTING: ./asset/results/training/VinDrMultiphase_Imagen_unet1/exp_0/model/fold1_checkpoint.pt
  
  unet_number: 2
  sample_quantity: 10000
  save_samples: True
  save_image_tensors: True
  cond_scale_testing: 5 # 1 to 10
  loss_weighting: p2
  text:
  phase:

  # Define Batch Boundaries to parallize sampling
  lower_batch: 0
  upper_batch: 100 

  # Kernel Inception Distance
  KernelInceptionDistance:
    usage: True
    params:
      feature: 2048
      subsets: 10
      subset_size: 1000
      reset_real_features: True
      normalize: True

  # Clean Fréchet Inception Distance
  CleanFID:
    usage: True
    params:
      mode: clean
      model_name: inception_v3
      num_workers: 4
      batch_size: 32 

  # Fréchet CLIP Distance
  FrechetCLIPDistance:
    usage: True
    params:
      mode: clean
      model_name: clip_vit_b_32
      num_workers: 4
      batch_size: 32 

  #
  LearnedPerceptualImagePatchSimilarity:
    usage: False
    params:
      net_type: vgg

### Wandb
wandb:
  wandb_prj: "MultiphaseBioImgGen"
  wandb_entity: "scalemind"