defaults:
  - conductor: default_imagen
  - model: imagen
  - data: vindr_multiphase
  - _self_

hydra:
  run:
    dir: ./results/${conductor.mode}/${data.name}_${model.name}/unet${conductor.unet}/${now:%Y-%m-%d}/${now:%H-%M-%S}