PATH_DATA_DIR: /mnt/sda1/home/bmestaging/duong/git/MultiphaseBioImgGen/
data:
  VinDrMultiphase:
    PATH_DICOM_DIR: ./data/source/vindr_multiphase/abdomen_phases
    PATH_METADATA_PROMPT_FILE: ./data/source/vindr_multiphase/metadata_prompt.csv
    PATH_PNG_DIR: ./data/source/vindr_multiphase/abdomen_phases_png
    PATH_T5_EMBEDDING_FILE: ./data/source/vindr_multiphase/t5_embeddings.pt
    classes:
      Aterial: aterial
      NonConstrast: non-contrast
      Venous: venous
    preprocessing:
      random_state: 42
      test_size: 0.1
      train_size: 0.8
      valid_size: 0.1
  dataset: VinDrMultiphase
  image_size: 256
  use_existing_data_files: true
log: false
