name: vindr_multiphase
PATH_DICOM_DIR: ././data/vindr_multiphase/abdomen_phases
PATH_METADATA_PROMPT_FILE: ./data/vindr_multiphase/metadata_prompt.csv

t5_embeddings:
  train: ./data/vindr_multiphase/t5_embeddings/train.pt
  valid: ./data/vindr_multiphase/t5_embeddings/valid.pt
  test: ./data/vindr_multiphase/t5_embeddings/test.pt

preprocessing:  
  window_center: 40
  window_width: 400

augmentation:
  image_size: 256
  horizontal_flip:
    p: 0.2
  shift_scale_rotate:
    shift_limit: 0.0625
    scale_limit: 0.1
    rotate_limit: 3
    p: 0.5


classes:
  Non-contrast: non contrast
  Arterial: arterial
  Venous: venous
  Others: others

num_classes: 4

num_train_sample: 
num_valid_sample: 
num_test_sample: 
num_train_batch:
num_valid_batch:
num_test_batch: